#!/bin/sh

sudo chmod +x ./*

if [ -d "/home/$USER/.local/share/kite" ]
then
        echo "KITE is alread installed"
else
        echo "install KITE"
        bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
fi

if [ -d "/home/$USER/.local/share/nvim/site/autoload" ]
then
        echo "plug.vim is already installed"
else
        echo "Install plug.vim"
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi

if [ -d "/home/$USER/.config/nvim" ]
then
	    echo "Change init.vim"
else
	    echo "Make directory at .config/nvim"
fi

SHELL_PATH=$(dirname $(realpath $0))
rm -f ~/.config/nvim/init.vim
ln -s $SHELL_PATH/init.vim ~/.config/nvim/init.vim
ln -s $SHELL_PATH/coc.vim ~/.config/nvim/language.vim
ln -s $SHELL_PATH/kite.vim ~/.config/nvim/kite.vim
