#!/bin/sh

#sudo chmod +x ./*
SHELL_PATH=$(dirname $(realpath $0))

if [-d "/home/$USER/.vim/bundle/nerdtree/LICENCE"]
then
        echo "nerdtree is already installed"
else
        echo "install nerdtree"
        git clone https://github.com/preservim/nerdtree.git ~/.vim/bundle/nerdtree
fi


rm ~/.vimrc
rm -r ~/.vim
ln -s $SHELL_PATH/.vimrc ~/.vimrc
ln -s $SHELL_PATH/ ~/.vim
