#!/bin/sh

sudo chmod +x ./*

if [ -d "/home/$USER/.local/share/kite" ]
then
        echo "KITE is alread installed"
else
        echo "install KITE"
        bash -c "$(wget -q -O - https://linux.kite.com/dls/linux/current)"
fi


SHELL_PATH=$(dirname $(realpath $0))
ln -s $SHELL_PATH/.vimrc ~/.vimrc

